{
 "title": "Kafka Streams",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "thread_id",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_commit_latency_max,thread_id)"
    }
   },
   {
    "name": "task_id",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_total,task_id)"
    }
   },
   {
    "name": "processor_node_id",
    "query": {
     "query": "label_values(kafka_streams_stream_processor_node_metrics_process_rate,processor_node_id)"
    }
   },
   {
    "name": "record_cache_id",
    "query": {
     "query": "label_values(kafka_streams_stream_record_cache_metrics_hit_ratio_avg,record_cache_id)"
    }
   },
   {
    "name": "rocksdb_state_id",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_get_latency_max,rocksdb_state_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Thread metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Processed Records"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Polls"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Commits"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Punctuated Records"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_created_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Tasks Created"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_task_closed_total{thread_id=\"$thread_id\"}",
       "legendFormat": "Tasks Closed"
      }
     ]
    },
    {
     "title": "Task Created Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_created_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "Task Created Rate"
      }
     ]
    },
    {
     "title": "Task Closed Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_closed_rate{thread_id=\"$thread_id\"}",
       "legendFormat": "Task Closed Rate"
      }
     ]
    },
    {
     "title": "Process Latency",
     "type": "timeseries",
     "description": "The average and max execution time in ms, for process, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_max{thread_id=\"$thread_id\"}",
       "legendFormat": "Max Process Latency"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{thread_id=\"$thread_id\"}",
       "legendFormat": "Avg Process Latency"
      }
     ]
    },
    {
     "title": "Process Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_rate{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Process Rate"
      }
     ]
    },
    {
     "title": "Process Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_ratio{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Process Ratio"
      }
     ]
    },
    {
     "title": "Poll Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for poll, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{thread_id=\"$thread_id\"}",
       "legendFormat": "Max Thread Poll Latency"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{thread_id=\"$thread_id\"}",
       "legendFormat": "Avg Thread Poll Latency"
      }
     ]
    },
    {
     "title": "Poll Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_rate{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Poll Rate"
      }
     ]
    },
    {
     "title": "Poll Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_ratio{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Poll Ratio"
      }
     ]
    },
    {
     "title": "Commit Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for commit, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{thread_id=\"$thread_id\"}",
       "legendFormat": "Max Thread Commit Latency"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{thread_id=\"$thread_id\"}",
       "legendFormat": "Avg Thread Commit Latency"
      }
     ]
    },
    {
     "title": "Commit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_rate{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Commit Rate"
      }
     ]
    },
    {
     "title": "Commit Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_ratio{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Commit Ratio"
      }
     ]
    },
    {
     "title": "Punctuate Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for punctuate, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{thread_id=\"$thread_id\"}",
       "legendFormat": "Max Thread Punctuate Latency"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{thread_id=\"$thread_id\"}",
       "legendFormat": "Avg Thread Punctuate Latency"
      }
     ]
    },
    {
     "title": "Punctuate Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_rate{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Punctuate Rate"
      }
     ]
    },
    {
     "title": "Punctuate Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_ratio{thread_id=\"$thread_id\"}",
       "legendFormat": "Thread Punctuate Ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Processed Records - {{task_id}}"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_commit_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Commits - {{task_id}}"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_dropped_records_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Punctuated Records - {{task_id}}"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_dropped_records_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Dropped Records - {{task_id}}"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_enforced_processing_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Enforced Processing - {{task_id}}"
      }
     ]
    },
    {
     "title": "Task Process Latency",
     "type": "timeseries",
     "description": "The average and max execution time in ms, for process, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_latency_max{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Max Process Latency"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_process_latency_avg{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Avg Process Latency"
      }
     ]
    },
    {
     "title": "Task Process Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}"
      }
     ]
    },
    {
     "title": "Enforced Processing Rate",
     "type": "graph",
     "description": "The average number of enforced processings per second for this task.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_enforced_processing_rate{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Enforced Processing Rate"
      }
     ]
    },
    {
     "title": "Commit Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for commit, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Max Thread Commit Latency"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_commit_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Avg Thread Commit Latency"
      }
     ]
    },
    {
     "title": "Commit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Thread Commit Rate"
      }
     ]
    },
    {
     "title": "Record Lateness",
     "type": "graph",
     "description": "The average and max execution time in ms, for poll, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_record_lateness_max{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Max Record Lateness"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_record_lateness_avg{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Avg Record Lateness"
      }
     ]
    },
    {
     "title": "Punctuate Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for punctuate, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_punctuate_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Max Thread Punctuate Latency"
      },
      {
       "expr": "kafka_streams_stream_task_metrics_punctuate_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Avg Thread Punctuate Latency"
      }
     ]
    },
    {
     "title": "Punctuate Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_punctuate_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Thread Punctuate Rate"
      }
     ]
    },
    {
     "title": "Active Process Ratio",
     "type": "graph",
     "description": "The fraction of time the thread spent on processing this active task among all assigned active tasks.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_active_process_ratio{thread_id=~\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Dropped Record Rate",
     "type": "graph",
     "description": "The average number of records dropped within this task.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_dropped_records_rate{thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
       "legendFormat": "Dropped Record Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor Node metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "The total number of records processed by a source node.\n\nThe total number of records that have been emitted downstream from suppression operation nodes. Compare with the process-total metric(Records Processed) to determine how many updates are being suppressed.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_process_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}",
       "legendFormat": "Records Processed - {{processor_node_id}}"
      },
      {
       "expr": "kafka_streams_stream_processor_node_metrics_suppression_emit_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}",
       "legendFormat": "Records Suppressed - {{processor_node_id}}"
      }
     ]
    },
    {
     "title": "Process Rate",
     "type": "timeseries",
     "description": "The average number of records processed per second by a source node.",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_process_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}"
      }
     ]
    },
    {
     "title": "Suppression Emit Rate",
     "type": "timeseries",
     "description": "The rate at which records that have been emitted downstream from suppression operation nodes. Compare with the process-rate metric to determine how many updates are being suppressed.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_suppression_emit_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}"
      }
     ]
    },
    {
     "title": "Record e2e Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for commit, across all running tasks of this thread.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_record_e2e_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}",
       "legendFormat": "Max record e2e Latency"
      },
      {
       "expr": "kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}",
       "legendFormat": "Avg record e2e Latency"
      },
      {
       "expr": "kafka_streams_stream_processor_node_metrics_record_e2e_latency_min{thread_id=\"$thread_id\",task_id=~\"$task_id\",processor_node_id=~\"$processor_node_id\"}",
       "legendFormat": "Min record e2e Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Record Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Record Cache Hit Ratio",
     "type": "graph",
     "description": "The [average | minimum | maximum] cache hit ratio defined as the ratio of cache read hits over the total cache read requests.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",record_cache_id=~\"$record_cache_id\"}",
       "legendFormat": "Max Record Cache Hit Ratio - {{thread_id}} - {{task_id}} - {{record_cache_id}}"
      },
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",record_cache_id=~\"$record_cache_id\"}",
       "legendFormat": "Avg Record Cache Hit Ratio - {{thread_id}} - {{task_id}} - {{record_cache_id}}"
      },
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_min{thread_id=\"$thread_id\",task_id=~\"$task_id\",record_cache_id=~\"$record_cache_id\"}",
       "legendFormat": "Min Record Cache Hit Ratio - {{thread_id}} - {{task_id}} - {{record_cache_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Put Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for put state operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max Put Latency - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg Put Latency - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Put Rate",
     "type": "graph",
     "description": "The average rate of put state operations per second for this store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Put Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Put If Absent Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for put state if absent operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Put If Absent Latency - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Put If Absent Latency - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Put If Absent Rate",
     "type": "graph",
     "description": "The average rate of put state if absent operations per second for this store.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Put If Absent Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Get Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for get state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_get_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Get Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_get_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Get Latency"
      }
     ]
    },
    {
     "title": "Get Rate",
     "type": "graph",
     "description": "The average rate of get state operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_get_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Get Rate"
      }
     ]
    },
    {
     "title": "Delete Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for delete state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Delete Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Delete Latency"
      }
     ]
    },
    {
     "title": "Delete Rate",
     "type": "graph",
     "description": "The average rate of delete state operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Delete Rate"
      }
     ]
    },
    {
     "title": "Put All Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for put all state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Put All Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Put All Latency"
      }
     ]
    },
    {
     "title": "Put All Rate",
     "type": "graph",
     "description": "The average rate of put all state operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Put All Rate"
      }
     ]
    },
    {
     "title": "All Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for all state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_all_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State All Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_all_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State All Latency"
      }
     ]
    },
    {
     "title": "All Rate",
     "type": "graph",
     "description": "The average rate of all state operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_all_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State All Rate"
      }
     ]
    },
    {
     "title": "Range Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for range state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_range_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Range Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_range_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Range Latency"
      }
     ]
    },
    {
     "title": "Range Rate",
     "type": "graph",
     "description": "The average rate of range state operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_range_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Range Rate"
      }
     ]
    },
    {
     "title": "Flush Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for flush state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_flush_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Flush Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_flush_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Flush Latency"
      }
     ]
    },
    {
     "title": "Flush Rate",
     "type": "graph",
     "description": "The average rate of state flush operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_flush_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Flush Rate"
      }
     ]
    },
    {
     "title": "Restore Latency",
     "type": "graph",
     "description": "The average and max execution time in ms, for restore state operation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_max{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Max State Restore Latency"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{thread_id=\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg State Restore Latency"
      }
     ]
    },
    {
     "title": "Restore Rate",
     "type": "graph",
     "description": "The average rate of state restore operations per second for this store.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "State Restore Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Statistics-based metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "The number of current open files.\n\nThe total number of file errors that occurred.",
     "gridPos": { "h": 3, "w": 9, "x": 7, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(kafka_streams_stream_state_metrics_number_open_files{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"})",
       "legendFormat": "Open Files"
      },
      {
       "expr": "sum(kafka_streams_stream_state_metrics_number_file_errors_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"})",
       "legendFormat": "File open errors"
      }
     ]
    },
    {
     "title": "Bytes Written Rate",
     "type": "timeseries",
     "description": "The average number of bytes written per second to the RocksDB state store.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Bytes Written Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Bytes Read Rate",
     "type": "timeseries",
     "description": "The average number of bytes read per second from the RocksDB state store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Bytes Read Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Memtable Bytes Flushed Rate",
     "type": "timeseries",
     "description": "The average number of bytes flushed per second from the memtable to disk.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Memtable Bytes Flushed Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Memtable Hit Ratio",
     "type": "timeseries",
     "description": "The ratio of memtable hits, relative to all lookups to the memtable.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_hit_ratio{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Memtable Hit Ratio - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Block Cache Data Hit Ratio",
     "type": "timeseries",
     "description": "The ratio of block cache hits for data blocks, relative to all lookups for data blocks to the block cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_data_hit_ratio{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Block Cache Data Hit Ratio - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Block Cache Index Hit Ratio",
     "type": "timeseries",
     "description": "The ratio of block cache hits for index blocks, relative to all lookups for index blocks to the block cache.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_index_hit_ratio{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Block Cache Index Hit Ratio - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Block Cache Filter Hit Ratio",
     "type": "timeseries",
     "description": "The ratio of block cache hits for filter blocks, relative to all lookups for filter blocks to the block cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_filter_hit_ratio{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Block Cache Filter Hit Ratio - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Bytes Read Compaction Rate",
     "type": "timeseries",
     "description": "The average number of bytes read per second during compaction.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_compaction_rate{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Bytes Read Compaction Rate - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Avg Write Stall Duration",
     "type": "timeseries",
     "description": "The average duration of write stalls, in ms.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_avg{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Avg Write Stall Duration - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Total Write Stall Duration",
     "type": "timeseries",
     "description": "The total number of bytes read per second during compaction.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_total{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
       "legendFormat": "Total Write Stall Duration - {{thread_id}} - {{task_id}} - {{rocksdb_state_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Properties-based metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Unflushed Immutable Memtables",
   "type": "stat",
   "description": "The number of immutable memtables that have not yet been flushed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_immutable_mem_table{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Active Memtable size",
   "type": "timeseries",
   "description": "The approximate size of the active memtable in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_cur_size_active_mem_table{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "All Memtable size",
   "type": "timeseries",
   "description": "The approximate size of active and unflushed immutable memtables in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_cur_size_all_mem_tables{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Memtable size",
   "type": "timeseries",
   "description": "The approximate size of active, unflushed immutable, and pinned immutable memtables in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_size_all_mem_tables{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Active Memtable entries",
   "type": "stat",
   "description": "The number of entries in the active memtable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_entries_active_mem_table{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Immutable Memtable entries",
   "type": "stat",
   "description": "The number of entries in the unflushed immutable memtables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_entries_imm_mem_tables{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Active Memtable Delete entries",
   "type": "stat",
   "description": "The number of delete entries in the active memtable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_deletes_active_mem_table{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Immutable Memtable Delete entries",
   "type": "stat",
   "description": "The number of delete entries in the unflushed immutable memtables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_deletes_imm_mem_tables{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Memtable Pending Flush",
   "type": "stat",
   "description": "This metric reports 1 if a memtable flush is pending, otherwise it reports 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_mem_table_flush_pending{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Flushes",
   "type": "stat",
   "description": "The number of currently running flushes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_running_flushes{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Compaction Pending",
   "type": "stat",
   "description": "This metric reports 1 if at least one compaction is pending, otherwise it reports 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_compaction_pending{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "stat",
   "description": "The number of currently running compactions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_running_compactions{thread_id=~\"$thread_id\",task_id=~\"$task_id\",rocksdb_state_id=~\"$rocksdb_state_id\"}",
     "legendFormat": "Thread - {{thread_id}} Task - {{task_id}} RocksDB - {{rocksdb_state_id}}"
    }
   ]
  }
 ]
}