apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-jmx
  labels:
    app: kafka-streams-jmx
spec:
  ports:
  - port: 7071
    name: jmx
  # clusterIP: None
  selector:
    app: kafka-streams-jmx